language: node_js
node_js:
  - 0.10
  - 0.11
  - 0.12
  - iojs
before_script:
  - npm install -g grunt-cli
notifications:
  email: false
  slack:
    rooms:
      - secure: CxoosG6eicpnlsSYf2EaETAibGA6N2Zrp8bWinvr0xgbUf39r8jLdnPWJIHPN++HG4gmpkUH/sYPUGbFE8AUpRIqtrT8uSRvBTK70AWA57gN9IfeXLKrDqmZFTAptIXK/RSVgYfe+szsWQ5/soXZleepoVjB21vEfgQl1HeDwAZ/+FXloYAh1tsKvuk22nx9JyqFflDIKxTXrdmhMolafI1eMgg9UAoXjn6r2tNQtvV2Ts4a2czfei9kflUsrEzWv8W2qZrGQukDQXeP98Ndvn27i/UQcbCTLQO11hy0yUDcVzNls0db2bZyMziFtSUX4LHAMWeCk4sUJ598512QA44bjqJt6LSYCZOTCcfwULfHKf0cEBV455Q2hJcuSfUzi3JOYqD4T3YxoiL8drB0GbcxZOnFtwRAL8BpVWwhA6//xeynvfJhhzOvi9HqIUKSW4OuNT0ODMKtEPu9PMdXlM88VTeohspEAF9QZnax5GpsvnaeU51fPbvkJMr+5AUHB74pIiIiJXxjwXlLsTOBgTy5cFfRtzhZzIPYZzEjoNLpM+XhE9WKFVb73MUV3g7TWkY7Va8P6KJGkUo2BACZIgPX6ZKdZ510cYxNqz+hsjdzZQ9lW78NCjpSUMUFlE/GyHskAz0XNhsqn7rt+ZbMeB/2tN4F5268F/499MnW72E=
    on_success: always
    on_failure: always
