language: node_js
node_js:
  - 0.10
  - 0.11
  - 0.12
  - iojs
before_script:
  - npm install -g grunt-cli
notifications:
  email: false
  slack:
    rooms:
      - secure: fOlTK5hKs3Cv3wJCn85tCQEjsZIhz6FRlf/mNR41Hp3g8ljPvJO9Ls67t1tV2gOVwNbzTd5NUTfK4qmWhYyYmvkzTG1j6IJXJ/zkz2CvvoiCZu/7ECHFGeyvvCKjrhETrkTs6eYjPBIAGBL6qNGD9Bv9gUlDjQyx2Yv45e+n2pI=
    on_success: always
    on_failure: always
